package session

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// jsonlLine is the subset of a Claude Code transcript line the parser reads.
// The JSONL schema is assumption A3 (INTERFACES.md §8): parse tolerantly and
// skip anything unrecognized rather than failing the whole transcript.
type jsonlLine struct {
	Type      string `json:"type"` // user | assistant | summary | system | ...
	IsMeta    bool   `json:"isMeta"`
	SessionID string `json:"sessionId"`
	CWD       string `json:"cwd"`
	GitBranch string `json:"gitBranch"`
	Summary   string `json:"summary"` // harness-generated session summary on type=="summary" lines
	Message   *struct {
		Role    string          `json:"role"`
		Model   string          `json:"model"`
		Content json.RawMessage `json:"content"` // string or []block
	} `json:"message"`
}

// metaPrefixes marks harness-injected content that is not part of the
// conversation: slash-command records, local-command caveats and output, and
// system reminders. Blocks starting with these are dropped from the envelope.
var metaPrefixes = []string{
	"<local-command-caveat>",
	"<local-command-stdout>",
	"<command-name>",
	"<command-message>",
	"<command-args>",
	"<system-reminder>",
	"Caveat: The messages below were generated by the user while running local commands",
}

func isMetaText(s string) bool {
	t := strings.TrimSpace(s)
	for _, p := range metaPrefixes {
		if strings.HasPrefix(t, p) {
			return true
		}
	}
	return false
}

type jsonlBlock struct {
	Type string `json:"type"`
	Text string `json:"text"`
}

// ParsedTranscript is the result of reading a Claude Code session JSONL file.
type ParsedTranscript struct {
	Turns     []Turn
	SessionID string
	CWD       string
	GitBranch string
	Model     string
	// Summary is Claude Code's own generated session summary (the text its
	// session picker shows) — the preferred default share topic. Last one in
	// the file wins. Empty for sessions not yet summarized.
	Summary string
}

// ParseJSONL reads a Claude Code session transcript. Thinking blocks and all
// tool activity (tool_use/tool_result) are excluded by design (privacy +
// tokens — shares carry only the conversation text); unknown line and block
// types are skipped.
func ParseJSONL(path string) (*ParsedTranscript, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening transcript: %w", err)
	}
	defer f.Close()

	pt := &ParsedTranscript{}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 1<<20), 32<<20)
	for sc.Scan() {
		raw := sc.Bytes()
		if len(raw) == 0 {
			continue
		}
		var line jsonlLine
		if err := json.Unmarshal(raw, &line); err != nil {
			continue // tolerate non-JSON or foreign lines
		}
		if line.SessionID != "" && pt.SessionID == "" {
			pt.SessionID = line.SessionID
		}
		if line.CWD != "" && pt.CWD == "" {
			pt.CWD = line.CWD
		}
		if line.GitBranch != "" && pt.GitBranch == "" {
			pt.GitBranch = line.GitBranch
		}
		if line.Type == "summary" && strings.TrimSpace(line.Summary) != "" {
			pt.Summary = strings.TrimSpace(line.Summary)
		}
		if line.Message == nil || line.IsMeta || (line.Type != "user" && line.Type != "assistant") {
			continue
		}
		if line.Message.Model != "" {
			pt.Model = line.Message.Model
		}
		blocks := parseContent(line.Message.Content)
		if len(blocks) == 0 {
			continue
		}
		pt.Turns = append(pt.Turns, Turn{Role: line.Message.Role, Blocks: blocks})
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("reading transcript: %w", err)
	}
	if len(pt.Turns) == 0 {
		return nil, fmt.Errorf("no conversation turns found in %s", path)
	}
	return pt, nil
}

func parseContent(raw json.RawMessage) []Block {
	if len(raw) == 0 {
		return nil
	}
	var s string
	if err := json.Unmarshal(raw, &s); err == nil {
		if s == "" || isMetaText(s) {
			return nil
		}
		return []Block{{Type: "text", Text: s}}
	}
	var jbs []jsonlBlock
	if err := json.Unmarshal(raw, &jbs); err != nil {
		return nil
	}
	var out []Block
	for _, jb := range jbs {
		switch jb.Type {
		case "text":
			if jb.Text != "" && !isMetaText(jb.Text) {
				out = append(out, Block{Type: "text", Text: jb.Text})
			}
		default:
			// thinking, tool_use, tool_result and unknown block types are
			// dropped: shares carry only the conversation text. A turn whose
			// blocks all drop (e.g. a tool_result-only user line) is skipped
			// whole by the len(blocks)==0 check in ParseJSONL.
		}
	}
	return out
}
