package session

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sampleJSONL = `{"type":"summary","summary":"Fixing auth","leafUuid":"x"}
{"type":"user","isMeta":true,"sessionId":"abc-123","message":{"role":"user","content":"injected meta line"}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands</local-command-caveat>"}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":[{"type":"text","text":"<command-name>/clear</command-name>"},{"type":"text","text":"<system-reminder>ignore me</system-reminder>"}]}}
{"type":"user","sessionId":"abc-123","cwd":"/home/alice/proj","gitBranch":"main","message":{"role":"user","content":"The token refresh loop is 401ing"}}
{"type":"assistant","sessionId":"abc-123","message":{"role":"assistant","model":"claude-fable-5","content":[{"type":"thinking","thinking":"private reasoning"},{"type":"text","text":"Looking at auth/manager.go"},{"type":"tool_use","id":"toolu_1","name":"Bash","input":{"command":"go test ./..."}}]}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"toolu_1","content":[{"type":"text","text":"FAIL: TestRefresh"}]}]}}
{"type":"system","subtype":"other"}
not-json-line
`

func writeSample(t *testing.T) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "abc-123.jsonl")
	if err := os.WriteFile(path, []byte(sampleJSONL), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestParseJSONL(t *testing.T) {
	pt, err := ParseJSONL(writeSample(t))
	if err != nil {
		t.Fatal(err)
	}
	if pt.SessionID != "abc-123" || pt.CWD != "/home/alice/proj" || pt.Model != "claude-fable-5" {
		t.Fatalf("metadata: %+v", pt)
	}
	if pt.Summary != "Fixing auth" {
		t.Fatalf("summary: got %q want %q", pt.Summary, "Fixing auth")
	}
	if len(pt.Turns) != 3 {
		t.Fatalf("turns: got %d want 3", len(pt.Turns))
	}
	for _, turn := range pt.Turns {
		for _, b := range turn.Blocks {
			for _, leak := range []string{"private reasoning", "local-command-caveat", "command-name", "system-reminder", "injected meta line"} {
				if strings.Contains(b.Text, leak) {
					t.Fatalf("harness meta content must be excluded: %q", b.Text)
				}
			}
		}
	}
	if pt.Turns[0].Blocks[0].Text != "The token refresh loop is 401ing" {
		t.Fatalf("first real turn: %+v", pt.Turns[0])
	}
	if pt.Turns[2].Blocks[0].Type != "tool_result" || pt.Turns[2].Blocks[0].Text != "FAIL: TestRefresh" {
		t.Fatalf("tool_result flattening: %+v", pt.Turns[2].Blocks[0])
	}
}

func TestRedact(t *testing.T) {
	turns := []Turn{{Role: "user", Blocks: []Block{
		{Type: "text", Text: "my key is fmsgk_abc123_S3cretPart and jwt eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmMifQ.c2lnbmF0dXJlLXBhcnQ"},
		{Type: "tool_result", Text: "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI export done; AKIAIOSFODNN7EXAMPLE"},
		{Type: "text", Text: "-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n-----END RSA PRIVATE KEY-----"},
	}}}
	hits := Redact(turns)
	joined := ""
	for _, b := range turns[0].Blocks {
		joined += b.Text + "\n"
	}
	for _, leak := range []string{"S3cretPart", "wJalrXUtnFEMI", "AKIAIOSFODNN7EXAMPLE", "MIIE", "c2lnbmF0dXJl"} {
		if strings.Contains(joined, leak) {
			t.Fatalf("leaked %q in %q", leak, joined)
		}
	}
	if len(hits) < 4 {
		t.Fatalf("expected >=4 pattern families hit, got %v", hits)
	}
}

func TestRenderExchanges(t *testing.T) {
	tr := &Transcript{
		Title: "Fix auth", Surface: "claude-code", Fidelity: "verbatim",
		SharerAddress: "@bob_claude@example.com", SharedAt: 1754280000,
		Turns: []Turn{
			{Role: "user", Blocks: []Block{{Type: "text", Text: "hello"}}},
			{Role: "assistant", Blocks: []Block{
				{Type: "text", Text: "on it"},
				{Type: "tool_use", Name: "Bash", Input: map[string]any{"command": "go test"}},
			}},
			// tool_result-only user turn: belongs to the current exchange.
			{Role: "user", Blocks: []Block{{Type: "tool_result", Text: "HEAD-part\n" + strings.Repeat("x", 5000) + "\nTAIL-part"}}},
			{Role: "assistant", Blocks: []Block{{Type: "text", Text: "tests fail on refresh"}}},
			// A real user prompt: starts exchange 2.
			{Role: "user", Blocks: []Block{{Type: "text", Text: "fix it then"}}},
			{Role: "assistant", Blocks: []Block{{Type: "text", Text: "fixed"}}},
		},
	}
	bodies, contents := RenderExchanges(tr)
	if len(bodies) != 2 || len(contents) != 2 {
		t.Fatalf("expected 2 exchanges, got %d bodies / %d contents", len(bodies), len(contents))
	}
	first, second := bodies[0], bodies[1]
	for _, want := range []string{"# Fix auth", "@bob_claude@example.com", "2 messages", "**User:** hello", "🔧 tool: Bash", "````tool-output", "HEAD-part", "TAIL-part", "chars truncated"} {
		if !strings.Contains(first, want) {
			t.Fatalf("first body missing %q", want)
		}
	}
	if strings.Contains(first, strings.Repeat("x", toolResultCap+1)) {
		t.Fatal("tool result middle not truncated")
	}
	if strings.Contains(first, "fix it then") {
		t.Fatal("second prompt leaked into first exchange")
	}
	for _, want := range []string{"**User:** fix it then", "**Claude:** fixed"} {
		if !strings.Contains(second, want) {
			t.Fatalf("second body missing %q", want)
		}
	}
	if strings.Contains(second, "# Fix auth") {
		t.Fatal("provenance header should only be on the first message")
	}

	// contents must be the hash-stable basis for incremental re-share: no
	// provenance header (it embeds share time and running totals), and
	// identical for an exchange regardless of what was rendered after it.
	if strings.Contains(contents[0], "# Fix auth") || strings.Contains(contents[0], "2 messages") {
		t.Fatal("contents must not carry the provenance header")
	}
	if contents[1] != second {
		t.Fatal("non-first content should equal its body (no header to strip)")
	}
	longer := *tr
	longer.SharedAt = 1754280000 + 9999 // a later share...
	longer.Turns = append(append([]Turn{}, tr.Turns...),
		Turn{Role: "user", Blocks: []Block{{Type: "text", Text: "one more thing"}}},
		Turn{Role: "assistant", Blocks: []Block{{Type: "text", Text: "done"}}},
	) // ...of a session that grew
	_, contents2 := RenderExchanges(&longer)
	if len(contents2) != 3 || contents2[0] != contents[0] || contents2[1] != contents[1] {
		t.Fatal("existing exchanges' contents must be byte-identical across shares, or incremental re-share never matches")
	}
}

func TestTruncateMiddle(t *testing.T) {
	s := "AAAA" + strings.Repeat("m", 10000) + "ZZZZ"
	got := truncateMiddle(s, 1500)
	if len(got) > 1500+64 {
		t.Fatalf("over budget: %d", len(got))
	}
	if !strings.HasPrefix(got, "AAAA") || !strings.HasSuffix(got, "ZZZZ") {
		t.Fatal("head/tail not preserved")
	}
	if !strings.Contains(got, "chars truncated") {
		t.Fatal("cut marker missing")
	}
	if truncateMiddle("short", 1500) != "short" {
		t.Fatal("short strings must pass through")
	}
}

func TestRenderExchangesElides(t *testing.T) {
	turns := make([]Turn, 100)
	for i := range turns {
		// One giant exchange: only the first turn is a user prompt.
		role := "assistant"
		if i == 0 {
			role = "user"
		}
		turns[i] = Turn{Role: role, Blocks: []Block{{Type: "text", Text: strings.Repeat("y", exchangeCap/40)}}}
	}
	tr := &Transcript{Title: "big", Turns: turns}
	bodies, _ := RenderExchanges(tr)
	if len(bodies) != 1 {
		t.Fatalf("expected 1 exchange, got %d", len(bodies))
	}
	if len(bodies[0]) > exchangeCap+4096 {
		t.Fatalf("body over cap: %d", len(bodies[0]))
	}
	if !strings.Contains(bodies[0], "middle turns elided") {
		t.Fatal("elision marker missing")
	}
}
