package session

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sampleJSONL = `{"type":"summary","summary":"Fixing auth","leafUuid":"x"}
{"type":"user","isMeta":true,"sessionId":"abc-123","message":{"role":"user","content":"injected meta line"}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands</local-command-caveat>"}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":[{"type":"text","text":"<command-name>/clear</command-name>"},{"type":"text","text":"<system-reminder>ignore me</system-reminder>"}]}}
{"type":"user","sessionId":"abc-123","cwd":"/home/alice/proj","gitBranch":"main","message":{"role":"user","content":"The token refresh loop is 401ing"}}
{"type":"assistant","sessionId":"abc-123","message":{"role":"assistant","model":"claude-fable-5","content":[{"type":"thinking","thinking":"private reasoning"},{"type":"text","text":"Looking at auth/manager.go"},{"type":"tool_use","id":"toolu_1","name":"Bash","input":{"command":"go test ./..."}}]}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"toolu_1","content":[{"type":"text","text":"FAIL: TestRefresh"}]}]}}
{"type":"system","subtype":"other"}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":"<task-notification>a subagent finished</task-notification>"}}
{"type":"user","isSidechain":true,"sessionId":"abc-123","message":{"role":"user","content":"subagent prompt from a sidechain"}}
{"type":"assistant","isSidechain":true,"sessionId":"abc-123","message":{"role":"assistant","content":[{"type":"text","text":"subagent answer from a sidechain"}]}}
{"type":"system","subtype":"compact_boundary","sessionId":"abc-123","compactMetadata":{"trigger":"auto"}}
{"type":"user","isCompactSummary":true,"isVisibleInTranscriptOnly":true,"sessionId":"abc-123","message":{"role":"user","content":"This session is being continued from a previous conversation"}}
{"type":"user","sessionId":"other-999","message":{"role":"user","content":"a different session's prompt"}}
{"type":"assistant","sessionId":"other-999","message":{"role":"assistant","content":[{"type":"text","text":"a different session's answer"}]}}
not-json-line
`

func writeSample(t *testing.T) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "abc-123.jsonl")
	if err := os.WriteFile(path, []byte(sampleJSONL), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestParseJSONL(t *testing.T) {
	pt, err := ParseJSONL(writeSample(t), "abc-123")
	if err != nil {
		t.Fatal(err)
	}
	if pt.SessionID != "abc-123" || pt.CWD != "/home/alice/proj" || pt.Model != "claude-fable-5" {
		t.Fatalf("metadata: %+v", pt)
	}
	if pt.Summary != "Fixing auth" {
		t.Fatalf("summary: got %q want %q", pt.Summary, "Fixing auth")
	}
	// Tool activity is excluded at parse: the assistant's tool_use block is
	// dropped (its text block survives) and the tool_result-only user turn
	// disappears entirely.
	if len(pt.Turns) != 2 {
		t.Fatalf("turns: got %d want 2", len(pt.Turns))
	}
	for _, turn := range pt.Turns {
		for _, b := range turn.Blocks {
			for _, leak := range []string{"private reasoning", "local-command-caveat", "command-name", "system-reminder", "injected meta line", "go test ./...", "FAIL: TestRefresh",
				// Content that belongs to some other conversation: subagent
				// sidechains, the post-compaction recap of pre-boundary
				// history, another session's lines in the same file, and
				// harness task notifications delivered as user turns.
				"sidechain", "continued from a previous conversation", "different session", "task-notification"} {
				if strings.Contains(b.Text, leak) {
					t.Fatalf("excluded content leaked: %q", b.Text)
				}
			}
		}
	}
	if pt.Turns[0].Blocks[0].Text != "The token refresh loop is 401ing" {
		t.Fatalf("first real turn: %+v", pt.Turns[0])
	}
	if pt.Turns[1].Role != "assistant" || len(pt.Turns[1].Blocks) != 1 || pt.Turns[1].Blocks[0].Text != "Looking at auth/manager.go" {
		t.Fatalf("assistant turn should keep only its text block: %+v", pt.Turns[1])
	}
}

func TestRedact(t *testing.T) {
	turns := []Turn{{Role: "user", Blocks: []Block{
		{Type: "text", Text: "my key is fmsgk_abc123_S3cretPart and jwt eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmMifQ.c2lnbmF0dXJlLXBhcnQ"},
		{Type: "text", Text: "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI export done; AKIAIOSFODNN7EXAMPLE"},
		{Type: "text", Text: "-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n-----END RSA PRIVATE KEY-----"},
	}}}
	hits := Redact(turns)
	joined := ""
	for _, b := range turns[0].Blocks {
		joined += b.Text + "\n"
	}
	for _, leak := range []string{"S3cretPart", "wJalrXUtnFEMI", "AKIAIOSFODNN7EXAMPLE", "MIIE", "c2lnbmF0dXJl"} {
		if strings.Contains(joined, leak) {
			t.Fatalf("leaked %q in %q", leak, joined)
		}
	}
	if len(hits) < 4 {
		t.Fatalf("expected >=4 pattern families hit, got %v", hits)
	}
}

func TestRenderExchanges(t *testing.T) {
	tr := &Transcript{
		Title: "Fix auth", Surface: "claude-code", Fidelity: "verbatim",
		SharerAddress: "@bob_claude@example.com", SharedAt: 1754280000,
		Turns: []Turn{
			{Role: "user", Blocks: []Block{{Type: "text", Text: "hello"}}},
			// Consecutive assistant turns stay in the current exchange.
			{Role: "assistant", Blocks: []Block{{Type: "text", Text: "on it"}}},
			{Role: "assistant", Blocks: []Block{{Type: "text", Text: "tests fail on refresh"}}},
			// A real user prompt: starts exchange 2.
			{Role: "user", Blocks: []Block{{Type: "text", Text: "fix it then"}}},
			{Role: "assistant", Blocks: []Block{{Type: "text", Text: "fixed"}}},
		},
	}
	bodies, contents := RenderExchanges(tr)
	if len(bodies) != 2 || len(contents) != 2 {
		t.Fatalf("expected 2 exchanges, got %d bodies / %d contents", len(bodies), len(contents))
	}
	first, second := bodies[0], bodies[1]
	for _, want := range []string{"# Fix auth", "@bob_claude@example.com", "2 messages", "**User:** hello", "**Claude:** on it", "tests fail on refresh"} {
		if !strings.Contains(first, want) {
			t.Fatalf("first body missing %q", want)
		}
	}
	// Renderings must carry no tool activity in any form.
	for _, body := range bodies {
		for _, banned := range []string{"🔧", "tool-output"} {
			if strings.Contains(body, banned) {
				t.Fatalf("tool artifact %q leaked into rendering", banned)
			}
		}
	}
	if strings.Contains(first, "fix it then") {
		t.Fatal("second prompt leaked into first exchange")
	}
	for _, want := range []string{"**User:** fix it then", "**Claude:** fixed"} {
		if !strings.Contains(second, want) {
			t.Fatalf("second body missing %q", want)
		}
	}
	if strings.Contains(second, "# Fix auth") {
		t.Fatal("provenance header should only be on the first message")
	}

	// contents must be the hash-stable basis for incremental re-share: no
	// provenance header (it embeds share time and running totals), and
	// identical for an exchange regardless of what was rendered after it.
	if strings.Contains(contents[0], "# Fix auth") || strings.Contains(contents[0], "2 messages") {
		t.Fatal("contents must not carry the provenance header")
	}
	if contents[1] != second {
		t.Fatal("non-first content should equal its body (no header to strip)")
	}
	longer := *tr
	longer.SharedAt = 1754280000 + 9999 // a later share...
	longer.Turns = append(append([]Turn{}, tr.Turns...),
		Turn{Role: "user", Blocks: []Block{{Type: "text", Text: "one more thing"}}},
		Turn{Role: "assistant", Blocks: []Block{{Type: "text", Text: "done"}}},
	) // ...of a session that grew
	_, contents2 := RenderExchanges(&longer)
	if len(contents2) != 3 || contents2[0] != contents[0] || contents2[1] != contents[1] {
		t.Fatal("existing exchanges' contents must be byte-identical across shares, or incremental re-share never matches")
	}
}

func TestRedactText(t *testing.T) {
	in := "deploy key sk-ant-abcdefghijklmnop123 and note MY_PASSWORD=hunter22x"
	out, hits := RedactText(in)
	for _, leak := range []string{"sk-ant-abcdefghijklmnop123", "hunter22x"} {
		if strings.Contains(out, leak) {
			t.Fatalf("leaked %q in %q", leak, out)
		}
	}
	if len(hits) != 2 {
		t.Fatalf("expected 2 pattern families, got %v", hits)
	}
	if out2, hits2 := RedactText("nothing secret here"); out2 != "nothing secret here" || len(hits2) != 0 {
		t.Fatalf("clean text must pass through: %q %v", out2, hits2)
	}
}

func TestRenderSummary(t *testing.T) {
	meta := SummaryMeta{
		Title: "Fix auth", SharerAddress: "@bob_claude@example.com",
		Surface: "claude-code", SharedAt: 1754280000, TurnCount: 12,
	}
	root := RenderSummary(meta, "We fixed the token refresh loop.\n")
	for _, want := range []string{"# Fix auth", "Summary of a Claude session shared by @bob_claude@example.com", "claude-code", "12 turns summarised", "We fixed the token refresh loop."} {
		if !strings.Contains(root, want) {
			t.Fatalf("root summary missing %q in %q", want, root)
		}
	}

	meta.TurnCount = 0
	noCount := RenderSummary(meta, "body")
	if strings.Contains(noCount, "turns summarised") {
		t.Fatal("unknown turn count must omit the turns clause")
	}

	meta.TurnCount = 15
	meta.FollowUp = true
	follow := RenderSummary(meta, "More work done.")
	if !strings.Contains(follow, "*Updated summary ·") || !strings.Contains(follow, "15 turns summarised") {
		t.Fatalf("follow-up header wrong: %q", follow)
	}
	for _, banned := range []string{"# Fix auth", "shared by"} {
		if strings.Contains(follow, banned) {
			t.Fatalf("follow-up must not repeat the root header (%q): %q", banned, follow)
		}
	}
}

func TestRenderExchangesElides(t *testing.T) {
	turns := make([]Turn, 100)
	for i := range turns {
		// One giant exchange: only the first turn is a user prompt.
		role := "assistant"
		if i == 0 {
			role = "user"
		}
		turns[i] = Turn{Role: role, Blocks: []Block{{Type: "text", Text: strings.Repeat("y", exchangeCap/40)}}}
	}
	tr := &Transcript{Title: "big", Turns: turns}
	bodies, _ := RenderExchanges(tr)
	if len(bodies) != 1 {
		t.Fatalf("expected 1 exchange, got %d", len(bodies))
	}
	if len(bodies[0]) > exchangeCap+4096 {
		t.Fatalf("body over cap: %d", len(bodies[0]))
	}
	if !strings.Contains(bodies[0], "middle turns elided") {
		t.Fatal("elision marker missing")
	}
}
