package session

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sampleJSONL = `{"type":"summary","summary":"Fixing auth","leafUuid":"x"}
{"type":"user","isMeta":true,"sessionId":"abc-123","message":{"role":"user","content":"injected meta line"}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands</local-command-caveat>"}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":[{"type":"text","text":"<command-name>/clear</command-name>"},{"type":"text","text":"<system-reminder>ignore me</system-reminder>"}]}}
{"type":"user","sessionId":"abc-123","cwd":"/home/alice/proj","gitBranch":"main","message":{"role":"user","content":"The token refresh loop is 401ing"}}
{"type":"assistant","sessionId":"abc-123","message":{"role":"assistant","model":"claude-fable-5","content":[{"type":"thinking","thinking":"private reasoning"},{"type":"text","text":"Looking at auth/manager.go"},{"type":"tool_use","id":"toolu_1","name":"Bash","input":{"command":"go test ./..."}}]}}
{"type":"user","sessionId":"abc-123","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"toolu_1","content":[{"type":"text","text":"FAIL: TestRefresh"}]}]}}
{"type":"system","subtype":"other"}
not-json-line
`

func writeSample(t *testing.T) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "abc-123.jsonl")
	if err := os.WriteFile(path, []byte(sampleJSONL), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

func TestParseJSONL(t *testing.T) {
	pt, err := ParseJSONL(writeSample(t))
	if err != nil {
		t.Fatal(err)
	}
	if pt.SessionID != "abc-123" || pt.CWD != "/home/alice/proj" || pt.Model != "claude-fable-5" {
		t.Fatalf("metadata: %+v", pt)
	}
	if len(pt.Turns) != 3 {
		t.Fatalf("turns: got %d want 3", len(pt.Turns))
	}
	for _, turn := range pt.Turns {
		for _, b := range turn.Blocks {
			for _, leak := range []string{"private reasoning", "local-command-caveat", "command-name", "system-reminder", "injected meta line"} {
				if strings.Contains(b.Text, leak) {
					t.Fatalf("harness meta content must be excluded: %q", b.Text)
				}
			}
		}
	}
	if pt.Turns[0].Blocks[0].Text != "The token refresh loop is 401ing" {
		t.Fatalf("first real turn: %+v", pt.Turns[0])
	}
	if pt.Turns[2].Blocks[0].Type != "tool_result" || pt.Turns[2].Blocks[0].Text != "FAIL: TestRefresh" {
		t.Fatalf("tool_result flattening: %+v", pt.Turns[2].Blocks[0])
	}
}

func TestRedact(t *testing.T) {
	turns := []Turn{{Role: "user", Blocks: []Block{
		{Type: "text", Text: "my key is fmsgk_abc123_S3cretPart and jwt eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmMifQ.c2lnbmF0dXJlLXBhcnQ"},
		{Type: "tool_result", Text: "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI export done; AKIAIOSFODNN7EXAMPLE"},
		{Type: "text", Text: "-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n-----END RSA PRIVATE KEY-----"},
	}}}
	hits := Redact(turns)
	joined := ""
	for _, b := range turns[0].Blocks {
		joined += b.Text + "\n"
	}
	for _, leak := range []string{"S3cretPart", "wJalrXUtnFEMI", "AKIAIOSFODNN7EXAMPLE", "MIIE", "c2lnbmF0dXJl"} {
		if strings.Contains(joined, leak) {
			t.Fatalf("leaked %q in %q", leak, joined)
		}
	}
	if len(hits) < 4 {
		t.Fatalf("expected >=4 pattern families hit, got %v", hits)
	}
}

func TestRenderMarkdown(t *testing.T) {
	tr := &Transcript{
		Title: "Fix auth", Surface: "claude-code", Fidelity: "verbatim",
		SharerAddress: "@bob_claude@example.com", SharedAt: 1754280000,
		Turns: []Turn{
			{Role: "user", Blocks: []Block{{Type: "text", Text: "hello"}}},
			{Role: "assistant", Blocks: []Block{
				{Type: "text", Text: "on it"},
				{Type: "tool_use", Name: "Bash", Input: map[string]any{"command": "go test"}},
			}},
			{Role: "user", Blocks: []Block{{Type: "tool_result", Text: "ok\n" + strings.Repeat("x", 5000)}}},
		},
	}
	body := RenderMarkdown(tr)
	for _, want := range []string{"# Fix auth", "@bob_claude@example.com", "**User:** hello", "**Claude:** on it", "🔧 Bash", "…(truncated)"} {
		if !strings.Contains(body, want) {
			t.Fatalf("missing %q in body", want)
		}
	}
	if strings.Contains(body, strings.Repeat("x", toolResultCap+1)) {
		t.Fatal("tool result not truncated")
	}
}

func TestRenderMarkdownElides(t *testing.T) {
	turns := make([]Turn, 100)
	for i := range turns {
		turns[i] = Turn{Role: "user", Blocks: []Block{{Type: "text", Text: strings.Repeat("y", bodyCap/40)}}}
	}
	tr := &Transcript{Title: "big", Turns: turns}
	body := RenderMarkdown(tr)
	if len(body) > bodyCap+4096 {
		t.Fatalf("body over cap: %d", len(body))
	}
	if !strings.Contains(body, "middle turns elided") {
		t.Fatal("elision marker missing")
	}
}
